project_id = "tgeueuwagmdguqwowhev"

[functions.activate-subscription]
verify_jwt = false

[functions.admin-review-payment]
verify_jwt = false

[functions.admin-suspend-mess]
verify_jwt = false

[functions.get-member-pins]
verify_jwt = false