project_id = "tgeueuwagmdguqwowhev"

[functions.activate-subscription]
verify_jwt = false

[functions.admin-review-payment]
verify_jwt = false

[functions.admin-suspend-mess]
verify_jwt = false

[functions.get-member-pins]
verify_jwt = false

[functions.send-contact-reply]
verify_jwt = false

[functions.submit-contact-form]
verify_jwt = false

[functions.get-turnstile-key]
verify_jwt = false

[functions.submit-payment]
verify_jwt = false